### ISSUE TITLE
Some bugs after creating articles using the special tools - bold, italic and images

### ISSUE THREAD

**Issue by AlexanderStanev** [Team-Code-Ninjas/SpaceBlog#15]
![bug](https://cloud.githubusercontent.com/assets/25152695/24674117/077dfd84-1983-11e7-99e4-fe79634d8a52.png)
------
![bug2](https://cloud.githubusercontent.com/assets/25152695/24674140/1cb84b82-1983-11e7-85e6-4ac16edabc7a.png)

**Comment by AlexanderStanev** [comment]
![bug3](https://cloud.githubusercontent.com/assets/25152695/24674448/1a3620f4-1984-11e7-877f-7390d8690a38.png)

**Comment by stoyanov7** [comment]
When I create new article with image works fine.
![test-image](https://cloud.githubusercontent.com/assets/23521228/24675194/eadb2504-1986-11e7-816d-31c0f0984c9d.png)

The bug we have to fix is in Article page.
![article-problem](https://cloud.githubusercontent.com/assets/23521228/24675272/2e0ca0c8-1987-11e7-823d-47002ca5d49d.png)

**Comment by AlexanderStanev** [comment]
I believe that the length of the path matters. The first one was longer than the second one

![1](https://cloud.githubusercontent.com/assets/25152695/24680488/c26bb63e-1999-11e7-953f-f7a1662acdcb.png)
-------------------------------------------
![2](https://cloud.githubusercontent.com/assets/25152695/24680489/c2848876-1999-11e7-9012-fd2001cbf0ff.png)
